config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  resources :recipes, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @entries = Recipes::List.new.call
  end

  def show
    @entry = Recipes::Find.new.call(id: params[:id])
    render 'not_found', status: 404 unless @entry
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestMspoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand"></a>
    </div>
  </nav>
  <body>
    <%= yield %>
  </body>
  <footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
  </footer>
</html>

app/views/recipes/index.html.erb
<ul class='list-group'>
  <% @entries.each do |recipe| %>
    <li class='list-group-item list-group-item-secondary'>
      <h1 class='text-center'><%= link_to recipe.title, recipe_path(recipe.id), class: 'text-dark' %></h1>
      <img src="<%= recipe.photo.url %>" class="rounded mx-auto d-block w-50 p-3"/>
    </li>
  <% end %>
</ul>

app/views/recipes/not_found.html.erb
<div class="vh-100">
  <h1 class='text-center'>Oops! Not found!</h1>
</div>

app/views/recipes/show.html.erb
<ul class='list-group'>
  <li class='list-group-item list-group-item-secondary'>
    <h2> <%= @entry.title %> </h2>
    <div><img src="<%= @entry.photo.url %>" class="rounded float-left img-fluid"/></div>
  </li>
  <li class='list-group-item list-group-item-secondary border-0'>
    <% if @entry.fields.key?(:tags) %>
      <span class='badge badge-secondary'> <%= @entry.tags.map(&:name).join(', ') %> </span>
    <% end %>
  </li>
  <li class='list-group-item list-group-item-secondary border-0'>
    <p> <%= @entry.description %> </p>
  </li>
  <li class='list-group-item list-group-item-secondary'>
    <p> <%= @entry.chef.name if @entry.fields.key?(:chef) %></p>
  </li>
</ul>